name: Deploy to Linux VM

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}                # Use the HOST secret
          username: ${{ secrets.USERNAME }}        # Use the USERNAME secret
          key: ${{ secrets.SSH_PRIVATE_KEY }}      # Use the SSH_PRIVATE_KEY secret
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # Use the SSH_PASSPHRASE secret
          script: |
            cd ~/challenge                           # Change to the challenge directory
            git pull origin main                     # Pull the latest changes
            docker compose down                      # Stop and remove existing containers
            docker compose up --build                # Build and start containers
