name: Deploy to Linux VM

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Match this with your project's Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: 104.248.42.192                # Your droplet's IP address
          username: root                       # Use root as the username
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBzhQ6Ii4
            6KxtBiKKB7acBUAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIPPwO25YU8XB46gA
            +LgYX4547HJe7ZZsn7ZNcMbIqXJuAAAAoAQdwCZoi+/p4UDvB7zXa77RM+iPfhwLxw7RJo
            2dhc7KkspOhWp6gJO7ts5uJUzd8Ymti/3dttQBi9EumMwNy/0nivUS6Vf9xxSgLUZsI2o+
            dk6bQG9qfuOOovquhZrHlhFk8K6KDVH0TOd03NM4urz6YuWBkUX8Ux1WzXedaY1WJws4gq
            N+sSt/K9x/kqEB7qq0xd2vahrn5zHCg4lXfQQ=
            -----END OPENSSH PRIVATE KEY-----
          passphrase: vit                       # Passphrase for the SSH key
          script: |
            cd ~/your_project_directory             # Change to your project directory
            git pull origin main                     # Pull the latest changes
            docker compose down                      # Stop and remove existing containers
            docker compose up --build                # Build and start containers
